name: on_merge_contents

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - contents/blogPost/**/*.md

jobs:
  on_merge_contents:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Update changed-files
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Get changed files in the contents folder
        id: changed-files-specific
        uses: tj-actions/changed-files@4cd184a1dd542b79cca1d4d7938e4154a6520ca7 # v46.0.0
        with:
          files: |
            contents/**
          since_last_remote_commit: true
    outputs:
      added_files: ${{ steps.changed-files-specific.outputs.added_files }}
      modified_files: ${{ steps.changed-files-specific.outputs.modified_files }}
      deleted_files: ${{ steps.changed-files-specific.outputs.deleted_files }}

  update-contents:
    needs: on_merge_contents
    uses: ./.github/workflows/wf_update.yaml
    with:
      added_files: ${{ needs.on_merge_contents.outputs.added_files }}
      modified_files: ${{ needs.on_merge_contents.outputs.modified_files }}
      deleted_files: ${{ needs.on_merge_contents.outputs.deleted_files }}
    secrets:
      MANAGEMENT_TOKEN: ${{ secrets.MANAGEMENT_TOKEN }}
      PREVIEW_SPACE: ${{ secrets.PREVIEW_SPACE }}
