name: Update Blog Post

on:
  workflow_call:
    inputs:
      added_files:
        description: "新しく作成されたファイルパス"
        required: false
        type: string
        default: ""
      modified_files:
        description: "変更されたファイルパス"
        required: false
        type: string
        default: ""
      deleted_files:
        description: "削除されたファイルパス"
        required: false
        type: string
        default: ""
    secrets:
      MANAGEMENT_TOKEN:
        description: "Contentful Management Token"
        required: true
      PREVIEW_SPACE:
        description: "Preview Space ID"
        required: true

  workflow_dispatch:
    inputs:
      added_files:
        description: "新しく作成されたファイルパス"
        required: false
        type: string
        default: ""
      modified_files:
        description: "変更されたファイルパス"
        required: false
        type: string
        default: ""
      deleted_files:
        description: "削除されたファイルパス"
        required: false
        type: string
        default: ""

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
        with:
          node-version-file: package.json
          cache-dependency-path: "**/package-lock.json"
      - name: Update changed files
        run: npm run update -w=packages/content-management
        id: update
        env:
          ADDED_FILES: ${{ inputs.added_files }}
          MODIFIED_FILES: ${{ inputs.modified_files }}
          DELETED_FILES: ${{ inputs.deleted_files }}
          MANAGEMENT_TOKEN: ${{ secrets.MANAGEMENT_TOKEN }}
          SPACE: ${{ secrets.PREVIEW_SPACE }}
          ENVIRONMENTS: master
